name: Build on Tag

on:
  push:
    tags:
      - '*'  # only tags

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Check out repository
        uses: actions/checkout@v3

#      - name: Clone SDL2
#        run: git clone --depth=1 --branch release-2.30.9 https://github.com/libsdl-org/SDL.git external/SDL2

#      - name: SDL2 Framework
#        run: brew install sdl2

#      - name: Build SDL2
#        run: |
#          cd external/SDL2
#          mkdir build
#          cd build
#          cmake .. -DCMAKE_BUILD_TYPE=Release
#          cmake --build . --config Release
#          cd ../../..

      - name: Build for macOS
        run: make PLATFORM=macos

      - name: Install create-dmg
        run: brew install create-dmg

      - name: Create macOS installer
        run: make install-macos PLATFORM=macos

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/dm50.dmg
          asset_name: dm50.dmg
          asset_content_type: application/octet-stream
        
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install SDL2
        run: sudo apt-get update && sudo apt-get install -y libsdl2-dev

      - name: Build for Linux
        run: make PLATFORM=linux

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-binary
          path: build/bin/*

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Install SDL2
        run: choco install sdl2
        
      - name: Build for Windows
        run: make PLATFORM=windows
        
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-binary
          path: build/bin/*.exe
